
services:
  search-torrent:
    build: .
    container_name: search-torrent
    ports:
      - "4000:80"
    volumes:
      - ./data:/app/data  # Pour la base SQLite
    environment:
      - NODE_ENV=production
      - PORT=3001  # Port du backend
      - JWT_SECRET=change_this_to_a_secure_secret
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin # Changez-le ici pour le premier démarrage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped